<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VehicleDiagnosticsDashboard.Application\VehicleDiagnosticsDashboard.Application.csproj" />
    <ProjectReference Include="..\VehicleDiagnosticsDashboard.Domain\VehicleDiagnosticsDashboard.Domain.csproj" />
  </ItemGroup>

</Project>
